### ISSUE TITLE
captions displayed when there aren't any

### ISSUE THREAD

**Issue by falloutguy** [webplantmedia/wc-gallery#22]
I have a gallery in which only a few pictures have captions. When I view the fancy box there are (correctly) at first no captions. Once an image with caption has been displayed, that caption will stick until the next image with a different caption. I'm not sure if it's a bug or a "feature", but the same occurs when I move backwards (viewing images from last to first) so that definitely isn't helpful.

I can only provide a link to my gallery via private message at this time. However, all software is up to date (WP 4.1.1, WP Canvas Gallery 1.29).

**Comment by webplantmedia** [comment]
Thanks! I marked this as a bug and will look into it.

**Comment by webplantmedia** [comment]
I fixed this bug and will roll out an update for my plugin soon. Thanks for reporting it.
