### ISSUE TITLE
Slider with fade and "slideshow true" gets incorrect height value in Chrome & Safari

### ISSUE THREAD

**Issue by span** [webplantmedia/wc-gallery#27]
I was looking for an option to enable the fading slider in the GUI but could not find it. However, looking through the source I found an option to set `slideshow` to `true`. This worked fine in Firefox but in Chrome and Safari the height of my images would not render correctly until the first image swap.

I am planning to look into this and would absolutely submit a patch. I'm just curious if this is a known issue or if anyone have an idea on where to start looking. I found #25 and it might be related although that example is sliding the image, not fading it.

**Comment by webplantmedia** [comment]
I think this was a problem with the height being calculated before the image was loaded. I updated and fixed the issue with version 1.67
